# Environment (like as cluster name)
environment: stage-dp

ingress:
  enabled: true
  servicePort: 80
  ingressClassName: {{.Helm.Release.Namespace}}
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Resource-Id {{.Helm.Release.Namespace}};
    nginx.ingress.kubernetes.io/proxy-body-size: 6m

  hosts:
    - name: {{.Helm.Release.Namespace}}-ingress-controller.{{.Helm.Release.Namespace}}.svc.{{.Helm.Release.Cluster}}
      path: /
      servicePort: 80
      service: frontend-mediabasket
      tls: false
    - name: sd2-stage.wb.ru
      path: /
      servicePort: 80
      service: frontend-mediabasket
      tls: false
